name: Build and Deploy to Production

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  on-main-branch-check:
    runs-on: Linux
    outputs:
      on_main: ${{ steps.contains_tag.outputs.retval }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: rickstaa/action-contains-tag@v1
        id: contains_tag
        with:
          reference: "develop"
          tag: "${{ github.ref }}"
  build:
    runs-on: anton-builder
    needs: on-main-branch-check
    if: ${{ needs.on-main-branch-check.outputs.on_main == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build
        run: |
          ls -la
          eas build -p ios --local --non-interactive --output latest-build.ipa

  deploy_app:
    name: Deploy to test flight
    needs:
      - on-main-branch-check
      - build
    runs-on: anton-builder
    steps:
      - uses: actions/checkout@v3
      - name: deploy
        run: |
          ls -la
          eas submit --platform ios --path="latest-build.ipa" --non-interactive

      - name: Cleanup
        run: |
          ls -la
          rm -rf latest-build.ipa
          ls -la
